apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-playground
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hnaciri-1337/ARGOCD.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
