Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.define "haithamS" do |srv|
    srv.vm.hostname = "haithamS"
    srv.vm.network "private_network", ip: "192.168.56.110"

    srv.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "haithamS"]
    end

    srv.vm.provision "shell", path: "scripts/install_k3s.sh"
  end
end
