Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"


  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  # -----------------------------
  # Machine 1 : K3s SERVER
  # -----------------------------
  config.vm.define "hnaciriS" do |srv|
    srv.vm.hostname = "hnaciriS"
    srv.vm.network "private_network", ip: "192.168.56.110"

    srv.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "hnaciriS"]
    end

    srv.vm.provision "shell", path: "scripts/setup_ssh.sh"
    srv.vm.provision "shell", path: "scripts/install_server.sh"
  end

  # -----------------------------
  # Machine 2 : K3s WORKER
  # -----------------------------
  config.vm.define "hnaciriSW" do |wrk|
    wrk.vm.hostname = "hnaciriSW"
    wrk.vm.network "private_network", ip: "192.168.56.111"

    wrk.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "hnaciriSW"]
    end

    wrk.vm.provision "shell", path: "scripts/setup_ssh.sh"
    wrk.vm.provision "shell", path: "scripts/install_worker.sh"
  end
end
