Vagrant.configure("2") do |config|
  # Lightweight but stable
  config.vm.box = "ubuntu/jammy64"

  # VM resources (enough for Docker + k3d)
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 2
  end

  # VM identity
  config.vm.hostname = "iot-p3"

  # Port forwarding
  # ArgoCD UI
  config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true

  # Wil playground app
  config.vm.network "forwarded_port", guest: 1337, host: 1337, auto_correct: true
end
